/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "var(--tertiary-container)",
        "on-secondary": "var(--on-secondary)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "surface-tint": "var(--surface-tint)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "surface-dim": "var(--surface-dim)",
        "surface-bright": "var(--surface-bright)",
        "error-container": "var(--error-container)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "surface-container-high": "var(--surface-container-high)",
        "secondary-container": "var(--secondary-container)",
        "surface-container": "var(--surface-container)",
        "on-error-container": "var(--on-error-container)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "outline-variant": "var(--outline-variant)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "surface-container-low": "var(--surface-container-low)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "outline": "var(--outline)",
        "on-error": "var(--on-error)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-tertiary": "var(--on-tertiary)",
        "primary-fixed": "var(--primary-fixed)",
        "on-background": "var(--on-background)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "error": "var(--error)",
        "on-primary-container": "var(--on-primary-container)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-primary": "var(--on-primary)",
        "tertiary": "var(--tertiary)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "background": "var(--bg-primary)",
        "secondary": "var(--secondary)",
        "inverse-primary": "var(--inverse-primary)",
        "surface-variant": "var(--surface-variant)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "primary-container": "var(--primary-container)",
        "surface": "var(--surface)",
        "on-surface": "var(--on-surface)",
        "inverse-surface": "var(--inverse-surface)",
        "primary": "var(--primary)",
        "secondary-fixed": "var(--secondary-fixed)",
        /* ── shadcn/ui tokens ── */
        "border": "var(--border)",
        "input": "var(--input)",
        "ring": "var(--ring)",
        "foreground": "var(--foreground)",
        "card": { DEFAULT: "var(--card)", foreground: "var(--card-foreground)" },
        "popover": { DEFAULT: "var(--popover)", foreground: "var(--popover-foreground)" },
        "muted": { DEFAULT: "var(--muted)", foreground: "var(--muted-foreground)" },
        "accent": { DEFAULT: "var(--accent)", foreground: "var(--accent-foreground)" },
        "destructive": { DEFAULT: "var(--destructive)", foreground: "var(--destructive-foreground)" },
        "chart-1": "var(--chart-1)",
        "chart-2": "var(--chart-2)",
        "chart-3": "var(--chart-3)",
        "chart-4": "var(--chart-4)",
        "chart-5": "var(--chart-5)",
        "sidebar": {
          DEFAULT: "var(--sidebar)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      animation: {
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in": "fadeIn 0.3s ease-out forwards",
        "slide-up": "slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "sos-pulse": "sosPulse 1.5s infinite",
        shimmer: "shimmer 2s infinite linear",
        "radar-pulse": "radarPulse 3s infinite ease-out",
      },
      keyframes: {
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        sosPulse: {
          "0%": { transform: "scale(1)", boxShadow: "0 0 0 0 rgba(255, 68, 68, 0.7)" },
          "70%": { transform: "scale(1.05)", boxShadow: "0 0 0 15px rgba(255, 68, 68, 0)" },
          "100%": { transform: "scale(1)", boxShadow: "0 0 0 0 rgba(255, 68, 68, 0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-1000px 0" },
          "100%": { backgroundPosition: "1000px 0" },
        },
        radarPulse: {
          "0%": { transform: "translate(-50%, -50%) scale(0.5)", opacity: "1" },
          "100%": { transform: "translate(-50%, -50%) scale(2.5)", opacity: "0" },
        }
      },
      minHeight: { touch: '44px' },
      minWidth: { touch: '44px' },
    },
  },
  plugins: [],
};
