"""Healthsites.io Hospital Seeder — ONE-TIME script.

Pulls hospital data from Healthsites.io API to supplement OSM Overpass data.
Inserts into the emergency_services table in Supabase/PostGIS.

Usage:
    HEALTHSITES_TOKEN=your_token python scripts/seed_healthsites.py

Sign up free: https://healthsites.io/
"""

from __future__ import annotations

import os
import sys
import time
from pathlib import Path

import httpx

# Add project root to path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))


HEALTHSITES_URL = "https://healthsites.io/api/v2/facilities/"


def fetch_all_facilities(token: str, country: str = "IND") -> list[dict]:
    """Paginate through all facilities for a country."""
    facilities = []
    page = 1

    with httpx.Client(timeout=30.0) as client:
        while True:
            print(f"  Fetching page {page}...")
            response = client.get(
                HEALTHSITES_URL,
                params={"country": country, "page": page},
                headers={"Authorization": f"Token {token}"},
            )
            response.raise_for_status()
            data = response.json()

            results = data.get("results", [])
            if not results:
                break

            for fac in results:
                name = fac.get("name", "").strip()
                amenity = fac.get("attributes", {}).get("amenity", "")
                lat = fac.get("centroid", {}).get("coordinates", [None, None])[1]
                lon = fac.get("centroid", {}).get("coordinates", [None, None])[0]

                if name and lat and lon:
                    facilities.append({
                        "name": name,
                        "category": _map_amenity(amenity),
                        "lat": lat,
                        "lon": lon,
                        "source": "healthsites.io",
                        "uuid": fac.get("uuid", ""),
                    })

            # Check for next page
            if not data.get("next"):
                break

            page += 1
            time.sleep(1)  # Rate limit

    return facilities


def _map_amenity(amenity: str) -> str:
    """Map Healthsites amenity type to our category schema."""
    amenity = amenity.lower()
    if "hospital" in amenity:
        return "hospital"
    elif "clinic" in amenity:
        return "hospital"
    elif "pharmacy" in amenity:
        return "pharmacy"
    elif "doctors" in amenity:
        return "hospital"
    return "hospital"  # Default


def main() -> None:
    token = os.getenv("HEALTHSITES_TOKEN", "")
    if not token:
        print("❌ HEALTHSITES_TOKEN not set. Get a free token from healthsites.io")
        print("   Usage: HEALTHSITES_TOKEN=your_token python scripts/seed_healthsites.py")
        sys.exit(1)

    print("🏥 Healthsites.io Hospital Seeder")
    print("=" * 50)
    print(f"Fetching facilities for India...")

    facilities = fetch_all_facilities(token)
    print(f"\n✅ Fetched {len(facilities)} facilities from Healthsites.io")

    if not facilities:
        print("No facilities found. Check your token.")
        sys.exit(1)

    # Output as SQL for manual review / import
    output_file = ROOT / "backend" / "data" / "healthsites_seed.sql"
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("-- Healthsites.io hospital seed data\n")
        f.write("-- Generated by scripts/seed_healthsites.py\n\n")
        for fac in facilities:
            name = fac["name"].replace("'", "''")
            f.write(
                f"INSERT INTO emergency_services (name, category, location, source) "
                f"VALUES ('{name}', '{fac['category']}', "
                f"ST_SetSRID(ST_MakePoint({fac['lon']}, {fac['lat']}), 4326), "
                f"'healthsites.io') ON CONFLICT DO NOTHING;\n"
            )

    print(f"📁 SQL seed file written to: {output_file}")
    print(f"   Review and run: psql -d your_db -f {output_file}")


if __name__ == "__main__":
    main()
